on-unmatched = "debug"

[formatter.nix]
command = "nixfmt"
options = []
includes = [ "*.nix" ]
excludes = [ "_sources/*.nix" ]

[formatter.md]
command = "mdformat"
includes = [ "*.md" ]
excludes = [ "LICENSE.md" ]

[formatter.yaml]
command = "yamlfmt"
includes = [ "*.yaml", "*.yml" ]