# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mlnx-ofed-src = {
    pname = "mlnx-ofed-src";
    version = "25.01-0.6.0.0";
    src = fetchurl {
      url = "https://linux.mellanox.com/public/repo/mlnx_ofed/25.01-0.6.0.0/MLNX_OFED_SRC-debian-25.01-0.6.0.0.tgz";
      sha256 = "sha256-RDsWZdk18RQoSLxjfvJ+P3CmnlaIl9YMRqAuwIb1xls=";
    };
  };
}
